export const places = [
  { iconUrl: "/images/wifi.svg", name: "Wifi" },
  { iconUrl: "/images/tv.svg", name: "TV" },
  { iconUrl: "/images/kitchen.svg", name: "Kitchen" },
  { iconUrl: "/images/washingMachine.svg", name: "Washing machine" },
  { iconUrl: "/images/car.svg", name: "Free parking on premises" },
  { iconUrl: "/images/parkingMeter.svg", name: "Paid parking on premises" },
  { iconUrl: "/images/snowflake.svg", name: "Air conditioning" },
  { iconUrl: "/images/desk.svg", name: "Dedicated workspace" },
  { iconUrl: "/images/pool.svg", name: "Pool" },
  { iconUrl: "/images/tub.svg", name: "Hot tub" },
  { iconUrl: "/images/patio.svg", name: "Patio" },
  { iconUrl: "/images/bbq.svg", name: "BBQ grill" },
  { iconUrl: "/images/umbrellaTable.svg", name: "Outdoor dining area" },
  { iconUrl: "/images/firepit.svg", name: "Firepit" },
  { iconUrl: "/images/poolTable.svg", name: "Pool table" },
  { iconUrl: "/images/firePlace.svg", name: "Indoor fireplace" },
  { iconUrl: "/images/piano.svg", name: "Piano" },
  { iconUrl: "/images/fitnessCenter.svg", name: "Exercise equipment" },
  { iconUrl: "/images/lake.svg", name: "Lake access" },
  { iconUrl: "/images/beach.svg", name: "Beach access" },
  { iconUrl: "/images/skiing.svg", name: "Ski-in/out" },
  { iconUrl: "/images/shower.svg", name: "Outdoor shower" },
  { iconUrl: "/images/tire.svg", name: "Smoke alarm" },
  { iconUrl: "/images/firstAid.svg", name: "First aid kit" },
  { iconUrl: "/images/fireExtinguisher.svg", name: "Fire extinguisher" },
  { iconUrl: "/images/tireSqure.svg", name: "Carbon monoxide alarm" },
];
